name: flutter_clean_auth_architecture
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async_builder: 1.3.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  flutter_bloc: ^7.3.0
  flutter_loggy: 2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  infinite_listview: ^1.1.0
  internet_connection_checker: ^0.0.1+2
  loggy: 2.0.1
  provider: ^6.0.1
  rxdart: 0.27.2
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  bloc_test: ^8.1.0

flutter:
  assets:
    # - assets/images/
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
